/*
 * This file is part of Golaxy Distributed Service Development Framework.
 *
 * Golaxy Distributed Service Development Framework is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * Golaxy Distributed Service Development Framework is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Golaxy Distributed Service Development Framework. If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright (c) 2024 pangdogs.
 */

// Code generated by eventc eventtab --name=entityLibEventTab; DO NOT EDIT.

package pt

import (
	event "git.golaxy.org/core/event"
)

type IEntityLibEventTab interface {
	EventEntityLibDeclareEntityPT() event.IEvent
}

var (
	_entityLibEventTabId = event.DeclareEventTabIdT[entityLibEventTab]()
	EventEntityLibDeclareEntityPTId = _entityLibEventTabId + 0
)

type entityLibEventTab [1]event.Event

func (eventTab *entityLibEventTab) SetPanicHandling(autoRecover bool, reportError chan error) {
	for i := range *eventTab {
		(*eventTab)[i].SetPanicHandling(autoRecover, reportError)
	}
}

func (eventTab *entityLibEventTab) SetRecursion(recursion event.EventRecursion) {
	(*eventTab)[0].SetRecursion(event.EventRecursion_Allow)
}

func (eventTab *entityLibEventTab) SetEnable(b bool) {
	for i := range *eventTab {
		(*eventTab)[i].SetEnable(b)
	}
}

func (eventTab *entityLibEventTab) UnbindAll() {
	for i := range *eventTab {
		(*eventTab)[i].UnbindAll()
	}
}

func (eventTab *entityLibEventTab) Ctrl() event.IEventCtrl {
	return eventTab
}

func (eventTab *entityLibEventTab) Event(id uint64) event.IEvent {
	if _entityLibEventTabId != id & 0xFFFFFFFF00000000 {
		return nil
	}
	pos := id & 0xFFFFFFFF
	if pos >= uint64(len(*eventTab)) {
		return nil
	}
	switch pos {
	case 0:
		(*eventTab)[0].SetRecursion(event.EventRecursion_Allow)
	}
	return &(*eventTab)[pos]
}

func (eventTab *entityLibEventTab) EventEntityLibDeclareEntityPT() event.IEvent {
	(*eventTab).SetRecursion(event.EventRecursion_Allow)
	return &(*eventTab)[0]
}
