/*
 * This file is part of Golaxy Distributed Service Development Framework.
 *
 * Golaxy Distributed Service Development Framework is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * Golaxy Distributed Service Development Framework is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Golaxy Distributed Service Development Framework. If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright (c) 2024 pangdogs.
 */

// Code generated by eventc event; DO NOT EDIT.

package pt

import (
	event "git.golaxy.org/core/event"
	"git.golaxy.org/tiny/ec"
)

type iAutoEventEntityLibDeclareEntityPT interface {
	EventEntityLibDeclareEntityPT() event.IEvent
}

func BindEventEntityLibDeclareEntityPT(auto iAutoEventEntityLibDeclareEntityPT, subscriber EventEntityLibDeclareEntityPT, priority ...int32) event.Handle {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	return event.Bind[EventEntityLibDeclareEntityPT](auto.EventEntityLibDeclareEntityPT(), subscriber, priority...)
}

func _EmitEventEntityLibDeclareEntityPT(auto iAutoEventEntityLibDeclareEntityPT, entityPT ec.EntityPT) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventEntityLibDeclareEntityPT()).Emit(func(subscriber event.Cache) bool {
		event.Cache2Iface[EventEntityLibDeclareEntityPT](subscriber).OnEntityLibDeclareEntityPT(entityPT)
		return true
	})
}

func _EmitEventEntityLibDeclareEntityPTWithInterrupt(auto iAutoEventEntityLibDeclareEntityPT, interrupt func(entityPT ec.EntityPT) bool, entityPT ec.EntityPT) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventEntityLibDeclareEntityPT()).Emit(func(subscriber event.Cache) bool {
		if interrupt != nil {
			if interrupt(entityPT) {
				return false
			}
		}
		event.Cache2Iface[EventEntityLibDeclareEntityPT](subscriber).OnEntityLibDeclareEntityPT(entityPT)
		return true
	})
}

func HandleEventEntityLibDeclareEntityPT(fun func(entityPT ec.EntityPT)) EventEntityLibDeclareEntityPTHandler {
	return EventEntityLibDeclareEntityPTHandler(fun)
}

type EventEntityLibDeclareEntityPTHandler func(entityPT ec.EntityPT)

func (h EventEntityLibDeclareEntityPTHandler) OnEntityLibDeclareEntityPT(entityPT ec.EntityPT) {
	h(entityPT)
}
